version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: fitness_db
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend-dsl
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fitness_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      PARSER_INPUT_FILE: /app/data/example.txt  # Add this
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend-dsl:/app
      - ./data:/app/data  # Mount data directory

  frontend:
    build: 
      context: ./front
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: