version: '3.8'
services:
  my-spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Если нужно, укажите профиль
#    volumes: #  Раскомментируйте, если нужно монтировать volume
#      - ./:/app # Пример монтирования текущей директории в /app внутри контейнера.  Будьте осторожны с target директорией!